### ISSUE TITLE
Unable to select Tribe body parts

### ISSUE THREAD

**Issue by AtomixSpark** [Animus-Surge/wofrpg-releases#1]
Pre-Alpha 0.1.5

Windows 10

Tribe body parts cannot be selected. 
Process attempted 3x: Launched the game, logged in (clicked "remember me"), pressed play, selected empty slot (they don't seem to save your created and saved character when you close the game), went straight to the "appearance" tab and attempted to select a body part.
This happens for every slot at the bottom of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/74937655/100027368-a4623a80-2dba-11eb-86b5-1c04d9beca24.png)

LOG:
Log for some reason wasn't uploading to git despite being a supported file type of .log, so I've zipped it instead. I'll look into it on my end.

[update.zip](https://github.com/Animus-Surge/wofrpg-releases/files/5586446/update.zip)

**Comment by AtomixSpark** [comment]
Commenting with both a suggestion and a correction: I did not see the "tribes" and "roles" at the bottom of the screen on the Basic Info tab. This should be closer to the name and gender options, since my mind automatically assumed all that blank space meant there was nothing else on the tab.

**Comment by Animus-Surge** [comment]
Yeah, the UI is a big work in progress, and all that UI is gonna get changed pretty soon as to include better graphics and functionality. Gonna close this for now as it seems this has been resolved.
