### ISSUE TITLE
Lack of Environment Collission

### ISSUE THREAD

**Issue by AtomixSpark** [Animus-Surge/wofrpg-releases#2]
Pre-Alpha 0.1.5

Windows 10

Less a bug, more a "this was probably noticed already but I'm being sure"
You can stand on cliffs and on the void. I'm assuming there is simply no environment collision but I do not want to just assume if i can help it.

**Screenshots**
Mountain Goat
![image](https://user-images.githubusercontent.com/74937655/100030421-77fdec80-2dc1-11eb-8608-b29303d01679.png)
The Void
![image](https://user-images.githubusercontent.com/74937655/100030433-80562780-2dc1-11eb-8a33-919b9887e754.png)
Void 2
![image](https://user-images.githubusercontent.com/74937655/100030816-5b15e900-2dc2-11eb-9231-6543811d38ab.png)

**Log**
[update.log](https://github.com/Animus-Surge/wofrpg-releases/files/5586601/update.log)

**Comment by Animus-Surge** [comment]
TestMap has no collisions. Intentional.
